package aishe.gov.in.enums;

public interface Constant {
    String COLLEGE = "/college/";

    String UNIVERSITY = "/university/";
    String REQUEST_CANNOT_BE_PROCESSED = "Request Cannot Be Processed. Please Try Again.";
    String SUCCESS = "success";
    String UNAUTHORIZED_USER = "Unauthorised User(Token Expired)";
    String aishe_code = "aishe_code";
    String district_code = "district_code";

    String state_code = "state_code";

    String ONLY_DASH_ALLOWED_REGX="^[A-Za-z0-9]+(-[A-Za-z0-9]+)*$";



    String EXCEL_XLS_CONTENT_TYPE = "application/vnd.ms-excel";
    String CONTENT_DISPOSITION = "Content-Disposition";
    String WEBDCF_UNLOCK="/WebdcfUnlock/";
    String FINAL_SUBMITTED_PENDING="/final-submitted-pending/";
    int firstRow=1;

    int ZERO=0;
    String REGIONAL_CENTER_ONE="/regionalCenter1/";
    String SEPCIAL_PERMISSION="/SpecialPermission/";

    int freezeRow=6;
    Integer CHANGE_PASSWORD = 2;
    String NTA_QUESTION_DETAIL_QUERY="WITH NTQ(STATE_NAME,  DISTRICT, INSTITUTION_TYPE, MANAGEMENT, ONWERSHIP, AISHE_CODE, INSTITUTE_NAME, Q2, Q3, Q4, Q5_1, Q5_2_3, Q5_4, Q5_5, Q5_6, Q5_7, Q5_8, Q5_9, Q5_10, Q5_11, Q5_12, Q5_13, Q5_14, Q5_15, Q5_16, Q5_17, Q5_18, Q6_1, Q6_2, Q6_3, Q6_4, Q6_5, Q6_6, LATITUDE, LONGITUDE)AS (SELECT S.NAME AS STATE_NAME, DIST.NAME AS DISTRICT, RUCT.TYPE AS INSTITUTION_TYPE, RIM.MANAGEMENT, RIO.TYPE AS ONWERSHIP, NTQ.AISHE_CODE, NTQ.INSTITUTE_NAME, NTQ.Q2, NTQ.Q3, NTQ.Q4, NTQ.Q5_1, NTQ.Q5_2_3, NTQ.Q5_4, NTQ.Q5_5, NTQ.Q5_6, NTQ.Q5_7, NTQ.Q5_8, NTQ.Q5_9, NTQ.Q5_10, NTQ.Q5_11, NTQ.Q5_12, NTQ.Q5_13, NTQ.Q5_14, NTQ.Q5_15, NTQ.Q5_16, NTQ.Q5_17, NTQ.Q5_18, NTQ.Q6_1, NTQ.Q6_2, NTQ.Q6_3, NTQ.Q6_4, NTQ.Q6_5, NTQ.Q6_6, CLG.LATITUDE, CLG.LONGITUDE FROM MISCELLANEOUS.NTA_QUESTIONNAIRE NTQ LEFT JOIN INSTITUTE INS ON (INS.AISHE_CODE = NTQ.AISHE_CODE AND NTQ.AISHE_CODE IS NOT NULL) LEFT JOIN REF_STATE S ON S.ST_CODE = INS.STATE_ID LEFT JOIN REF_DISTRICT DIST ON DIST.DIST_CODE = INS.DISTRICT_ID LEFT JOIN REF_UNIVERSITY_COLLEGE_TYPE RUCT ON RUCT.ID = INS.TYPE_ID LEFT JOIN REF_INSTITUTION_MANAGEMENT RIM ON RIM.ID = INS.MANGEMENT_ID LEFT JOIN REF_INSTITUTION_OWNERSHIP RIO ON RIO.ID = CAST(INS.OWNER_SHIP_ID AS integer) LEFT JOIN COLLEGE_INSTITUTION CLG ON (NTQ.AISHE_CODE = 'C-' || CLG.ID AND CLG.SURVEY_YEAR = :surveyYear) WHERE INS.STATE_ID is not null AND NTQ.INSTITUTE_TYPE <> 'S' AND NTQ.INSTITUTE_TYPE <> 'U' AND (NTQ.INSTITUTE_TYPE = :institutionType OR 'ALL' = :institutionType)  AND (INS.STATE_ID = :stateId OR 'ALL' = :stateId) UNION ALL SELECT S.NAME AS STATE_NAME, DIST.NAME AS DISTRICT, RUT.TYPE AS INSTITUTION_TYPE, NULL AS MANAGEMENT, RIO.TYPE AS ONWERSHIP, NTQ.AISHE_CODE, NTQ.INSTITUTE_NAME, NTQ.Q2, NTQ.Q3, NTQ.Q4, NTQ.Q5_1, NTQ.Q5_2_3, NTQ.Q5_4, NTQ.Q5_5, NTQ.Q5_6, NTQ.Q5_7, NTQ.Q5_8, NTQ.Q5_9, NTQ.Q5_10, NTQ.Q5_11, NTQ.Q5_12, NTQ. Q5_13, NTQ.Q5_14, NTQ.Q5_15, NTQ.Q5_16, NTQ.Q5_17, NTQ.Q5_18, NTQ.Q6_1, NTQ.Q6_2, NTQ.Q6_3, NTQ.Q6_4, NTQ.Q6_5, NTQ.Q6_6, CLG.LATITUDE, CLG.LONGITUDE FROM MISCELLANEOUS.NTA_QUESTIONNAIRE NTQ LEFT JOIN INSTITUTE INS ON (INS.AISHE_CODE = NTQ.AISHE_CODE AND NTQ.AISHE_CODE IS NOT NULL) LEFT JOIN REF_STATE S ON S.ST_CODE = INS.STATE_ID LEFT JOIN REF_DISTRICT DIST ON DIST.DIST_CODE = INS.DISTRICT_ID LEFT JOIN REF_UNIVERSITY_TYPE RUT ON RUT.ID = INS.TYPE_ID LEFT JOIN REF_INSTITUTION_OWNERSHIP RIO ON RIO.ID = CAST(INS.OWNER_SHIP_ID AS integer) LEFT JOIN UNIVERSITY CLG ON (NTQ.AISHE_CODE = 'U-' || CLG.ID AND CLG.SURVEY_YEAR = :surveyYear) WHERE  INS.STATE_ID is not null AND NTQ.INSTITUTE_TYPE <> 'S' AND NTQ.INSTITUTE_TYPE <> 'C' AND (NTQ.INSTITUTE_TYPE = :institutionType OR 'ALL' = :institutionType)  AND (INS.STATE_ID = :stateId OR 'ALL' = :stateId) ) SELECT * FROM NTQ ORDER BY NTQ.STATE_NAME, NTQ.DISTRICT, NTQ.AISHE_CODE";


}
