import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { environment } from 'src/environments/environment';
import { LocalserviceService } from '../service/localservice.service';
import { EncryptDecrypt } from '../service/encrypt-decrypt';
const httpOptions = {
  headers: new HttpHeaders({
    'Access-Control-Allow-Origin': '*',
  })
}
@Injectable({
  providedIn: 'root'
})
export class MailerService {
  message: string = '';
  subject: string = '';
  roleName: any;
  userId: any;

  constructor(public http: HttpClient, public encrypt: EncryptDecrypt) {
  }

  sendEmail(condition: any, user: any, status: boolean): Observable<any> {
    if (condition === 'UserManagement') {
      if (status) {
        this.message = `Dear User,<br>You have been approved as role name ${user.roleName} with ${user.userId} user.`;
        this.subject = 'User Registration Approval';
      } else {
        this.message = `Dear User,<br>You have been disapproved as role name ${user.roleName} with ${user.userId} user.`;
        this.subject = 'User Registration DisApproval';
      }
    } else if (condition === 'UserRegister') {
      // this.message = `Dear User,\nYou have been successfully registered as <b>${user.roleName}</b> with user id <b>${user.userId}</b> on AISHE Portal.
      //                 \nPlease wait for your user approval from approving authority.\nYou may also contact the concerned approving authority for approval.
      //                 \nFollowing is your Approving Authority Contact Information whom you may contact:
      //                 \n<b>aishe-helpdesk[at]nic[dot]in</b>`

      this.message = `Dear User,<br><br>  You have been successfully registered as <B>${user.roleName}</B> with user id <B>${user.userId}
      				 </B> on AISHE Portal.<br>Please wait for your user approval from approving authority.
      				<br><br>You may also contact the concerned approving authority for approval.<br><br> 
      				 Following is your Approving Authority Contact Information whom you may contact:<B>aishe-helpdesk[at]nic[dot]in</B>`

      this.subject = 'New User Registration';


    }
    else if (condition === 'forgotPassword') {
     let userId =  this.encrypt.getEncryptedValue(user.userId.toString())
        this.message = `Dear User,<br><br> As requested, Password for the Email ID <B>${user.emailId}</B> can be reset by clicking on the below link :<br><br>
      ${environment.forgotComponent}${userId}<br><br><br>Thank you<br>Team AISHE<br><br>
      (This is an autogenerated mail kindly do not reply back.);`
      this.subject = 'Reset Password On AISHE Portal'
    }
    let payload = {
      "body": this.message,
      "emailAddress": user.emailId,
      "subject": this.subject
    }
    return this.http.post(`${environment.otpURL}send-any-email`, payload, httpOptions)
  }
}
