export const environment = {
  production: true,
  // downloadReportUrl:'https://demo.he.nic.in/aishe/',
  // baseUrl: 'https://api1.he.nic.in/aishereports/',
  // authLogin: 'https://api1.he.nic.in/auth/login',
  // baseUrlCaptcha: 'https://api1.he.nic.in/usermanagement/',
  // otpURL: 'https://demo.he.nic.in/aisheusermanagementdemo/',
  // masterUrl: `https://api1.he.nic.in/aishemasterservice`,
  // baseUrlAishe: `https://api1.he.nic.in/usermanagement/`,
  // dcfURL: 'https://demo1.he.nic.in/aishewebdcf/#/form/',
  // instituMURL: 'https://api1.he.nic.in/aisheinstitutemanagement',
  // instituDirectoryURL: 'https://api1.he.nic.in/aishereports/',
  // aisheHome:'https://demo.he.nic.in/aishehtml',
  // programmeUrl:'https://api1.he.nic.in/aishehibernatepostapi',
  // baseApi: 'https://api1.he.nic.in/aishereports/api/',
  // pdf: 'https://api1.he.nic.in/aishepdf/api/client',
  // baseUrlGetApi1: 'https://api1.he.nic.in/aishehibernategetapi',
  // baseUrlDetails:'https://api.aishe.gov.in'
  downloadReportUrl:'https://demo.he.nic.in/aishe/',
  baseUrl: 'https://api1.he.nic.in/aishereports/',
  authLogin: 'https://api1.he.nic.in/auth/login',
  baseUrlCaptcha:'https://api1.he.nic.in/usermanagement/',
  // baseUrlCaptcha: 'https://api1.he.nic.in/usermanagement/',
  otpURL: 'https://demo.he.nic.in/aisheusermanagementdemo/',
  masterUrl: `https://api1.he.nic.in/aishemasterservice`,
  baseUrlAishe: `https://api1.he.nic.in/usermanagement/`,
  dcfURL: 'https://demo.he.nic.in/aishewebdcf/#/form/',
  instituMURL: 'https://api1.he.nic.in/aisheinstitutemanagement',
  aisheHome: 'https://demo.he.nic.in/aishenew',
  instituDirectoryURL: 'https://api1.he.nic.in/aishereports/',
  programmeUrl: 'https://api1.he.nic.in/aishehibernatepostapi',
  pdf: 'https://api1.he.nic.in/aishepdf',
  baseUrlGetApi1: 'https://api1.he.nic.in/aishehibernategetapi',
  baseUrlDetails:'https://api.aishe.gov.in',
  baseURLRequest:'https://demo.he.nic.in/aisheusermanagementdemo/',

  baseURLLATLONG:'https://ministry.pmgatishakti.gov.in/lat-lon-api/auth/token',
  baseURLLATLONG1:'https://ministry.pmgatishakti.gov.in/lat-lon-api/',
  aisheMain:'https://demo.he.nic.in/aishenew',
  forgotComponent:'https://demo.he.nic.in/aishenew/#/datauserlogin/resetPassword/',
  baseUrlGetApi2: 'https://api1.he.nic.in/aishejpagetapi',
  baseUrlPostApi2:'https://api1.he.nic.in/aishejpapostapi',

};
